# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ray' do
	use_frameworks!

	# Pods for Ray
	pod 'Pageboy', '~> 3.0'
	pod 'Tabman', '~> 2.1'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
      	pod 'Firebase/Storage'
      	pod 'Firebase/Database'
	pod 'GoogleMaps'
	pod 'GooglePlaces'

end
